name: Push Helm chart to OCI

on:
  workflow_run:
    workflows: ["CI Version Bump"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
        id: checkout
        with:
          ref: main
      - uses: azure/setup-helm@v5
        id: install_helm
      - name: Add Helm repos & build dependencies
        run: |
          helm repo add valkey https://valkey.io/valkey-helm/
          helm dependency build ./n8n
      - name: Build Helm chart
        run: |
          helm package ./n8n
      - name: Login to Helm OCI
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ vars.OCI_REGISTRY }} --username ${{ github.repository_owner }} --password-stdin
      - name: Push Helm chart to OCI
        run: |
          helm push n8n-*.tgz oci://${{ vars.OCI_REGISTRY }}/${{ vars.OCI_REPOSITORY }}
      - name: Update README.md with Helm chart version
        run: |
          sed -i "s/--version .*/--version $(grep -oP '^version: \K.*' n8n/Chart.yaml)/" README.md
          rm n8n-*.tgz -f
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: "release: update README.md with Helm chart version"
          github_token: ${{ secrets.GITHUB_TOKEN }}
